[package]
name = "vehicle-manager-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
